---
title: 'IVD Example'
subtitle: "SROC"
author: "Yi"
date: "`r format(Sys.Date())`"
output: html_document
editor_options:
  chunk_output_type: console
params:
  p: NA
  n: NA
  sauc: "sauc"
  data: Null
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = TRUE, message=FALSE, comment="", fig.width = 10, fig.height = 10)
options(knitr.kable.NA = "")

library(knitr)
library(kableExtra)
library(latex2exp)
library(mvmeta)
library(meta)
library(dtametasa)


data <- params$data
#data.frame(study=seq(1:14)
#                             ,TP=c(12,10,17,13,4,15,45,18,5,8,5,11,5,7)
#                             ,FN=c(0,2,1,0,0,2,5,4,0,9,0,2,1,5)
#                             ,FP=c(29,14,36,18,21,122,28,69,11,15,7,122,6,25)
#                             ,TN=c(289,72,85,67,225,403,34,133,34,96,63,610,145,342))

## WHETHER TO SAVE PLOTS AND TABLES

save.results <- FALSE
# save.results <- TRUE

sauc.type <- params$sauc
```

# SROC plot results

```{r}
## SET SELECTION PROBABILITY p 

p.seq <- params$p

## ESITMATION WHEN c1, c2 ARE ESTIMATED

est2 <- sapply(p.seq, function(p) {
  
  opt2 <- dtametasa.rc(data, p, c1.square0  = 0.5, beta.interval = c(0,2), sauc.type = sauc.type)

  c(conv = opt2$convergence, opt2$sauc.ci, opt2$mu1.ci[4:6], opt2$mu2.ci[4:6], opt2$beta.ci, opt2$alpha, opt2$par)
  
})



## ESITMATION WHEN c1 = c2

est11 <- sapply(p.seq, function(p) {
  
  opt1 <- dtametasa.fc(data, p, c1.square  = 0.5, beta.interval = c(0,2), sauc.type = sauc.type)
  
  c(conv = opt1$convergence, opt1$sauc.ci, opt1$mu1.ci[4:6], opt1$mu2.ci[4:6], opt1$beta.ci, opt1$alpha, opt1$par, c1 = sqrt(0.5))
  
  })


## ESITMATION WHEN c1 = 1, c2 = 0

est10 <- sapply(p.seq, function(p) {
  
  opt1 <- dtametasa.fc(data, p, c1.square = 1, beta.interval = c(0,2), sauc.type = sauc.type)
  
  c(conv = opt1$convergence, opt1$sauc.ci, opt1$mu1.ci[4:6], opt1$mu2.ci[4:6], opt1$beta.ci, opt1$alpha, opt1$par, c1 = sqrt(1))
  
})


## ESITMATION WHEN c1 = 0, c2 = 1

est01 <- sapply(p.seq, function(p) {
  
  opt1 <- dtametasa.fc(data, p, c1.square  = 0, beta.interval = c(0,2), sauc.type = sauc.type)
  
  c(conv = opt1$convergence, opt1$sauc.ci, opt1$mu1.ci[4:6], opt1$mu2.ci[4:6], opt1$beta.ci, opt1$alpha, opt1$par, c1 = sqrt(0))
  
})


## RESULTS

colnames(est2)<- paste0("p = ", p.seq)

colnames(est11)<- paste0("p = ", p.seq)

colnames(est10)<- paste0("p = ", p.seq)

colnames(est01)<- paste0("p = ", p.seq)
```


# TABLE: ESTIMATES


```{r}

est <- est2

.reform.est <- function(est)
  {
    est <- est[-c(1, 20,21),]
    sauc.ci <- sprintf("%.3f (%.3f, %.3f)", est[1,], est[2,], est[3,])
    se.ci   <- sprintf("%.3f (%.3f, %.3f)", est[4,], est[5,], est[6,])
    sp.ci   <- sprintf("%.3f (%.3f, %.3f)", est[7,], est[8,], est[9,])
    b.ci    <- sprintf("%.3f (%.3f, %.3f)", est[10,], est[11,], est[12,])
    
    tb <- data.frame(p.seq=p.seq, 
                     sauc.ci= sauc.ci, 
                     se.ci = se.ci,
                     sp.ci = sp.ci,
                     b.ci = b.ci, 
                     round(t(est[-c(1:12),]),3)
                     )#[, -c(8:9, 13:14, 18:19)]
    
    colnames(tb) <- c("$p$", "SAUC (95\\%CI)",
                      "Se (95\\%CI)", "Sp (95\\%CI)",
                      "$\\beta$ (95\\%CI)", "$\\alpha_p$",
                      "$\\mu_1$", "$\\mu_2$", "$\\tau_1$","$\\tau_2$","$\\rho$"
                      )
    rownames(tb) <- NULL
    
    tb
    
    }


tb2  <- .reform.est(est2)
tb11 <- .reform.est(est11)
tb10 <- .reform.est(est10)
tb01 <- .reform.est(est01)

tb1 <- rbind(tb2, tb11, tb10, tb01)

tb1[c(1,5,9,13), 5] <- ""
tb1[c(1,5,9,13), 5:6] <- NA

tb <- cbind("$(c_1, \\,c_2)$" = c("$(\\hat{c}_1, \\hat{c}_2)$", rep("", 3),
                            "$(0.7, 0.7)$", rep("",3),
                            "$(1, 0)$", rep("", 3),
                            "$(0, 1)$", rep("", 3)),
             tb1)

if(save.results)  sink("~/Documents/GitHub/Manu1/SIM-2/SIM-ver2-supp-1221/TAB-RES-IVD.tex")

kbl(tb, 
    format =  ifelse(save.results, "latex", "html"),
    longtable = F, 
    booktabs = T, 
    digits = 3,
    align = "r",
    linesep = c(rep("",3), "\\addlinespace"),
    escape = FALSE,
    caption = "IVD example: the estimation under four selective publication mechanisms",
    label = "IVD")

if(save.results)  sink()
```


# SAUC matplot resuts

```{r, fig.height=6, fig.width=10}
p.10 <- seq(1, 0.1, -0.1)

## ESITMATION WHEN WE TREAT c1, c2 AS PARAMETERS

est.sauc2 <- sapply(p.10, function(p) {
  
  ## ESTIMATES OF THE PARAMETERS
  opt2 <- dtametasa.rc(data, p, beta.interval = c(0,2), sauc.type = sauc.type)

  c(opt2$sauc.ci)
  
})



## ESITMATION WHEN WE SET c1 = c2

est.sauc11 <- sapply(p.10, function(p) {
  
  opt1 <- dtametasa.fc(data, p,  c1.sq =0.5, beta.interval = c(0,2), sauc.type = sauc.type)
  
  c(opt1$sauc.ci)
  
  })

est.sauc10 <- sapply(p.10, function(p) {
  
  opt1 <- dtametasa.fc(data, p,  c1.sq = 1, beta.interval = c(0,2), sauc.type = sauc.type)
  
  c(opt1$sauc.ci)
  
  })

est.sauc01 <- sapply(p.10, function(p) {
  
  opt1 <- dtametasa.fc(data, p,  c1.sq = 0, beta.interval = c(0,2), sauc.type = sauc.type)
  
  c(opt1$sauc.ci)
  
  })


## ALL RESULTS

colnames(est.sauc2) <- colnames(est.sauc11) <- colnames(est.sauc10) <- colnames(est.sauc01) <- paste0("p = ", p.10)
```


# PLOT: SROC curve and corresponding SAUC


```{r, fig.width=10, fig.height=6}
# PLEASE CHOOSE ONE SAVED DATA *******

se <- data$TP/(data$TP+data$FN)
sp <- data$TN/(data$TN+data$FP)

est2.par  <- est2[15:19,]
est11.par <- est11[15:19,]
est10.par <- est10[15:19,]
est01.par <- est01[15:19,]

sauc2  <- est2[2,]
sauc11 <- est11[2,]
sauc10 <- est10[2,]
sauc01 <- est01[2,]

title.cex <- 1.5
legend.cex <- 1.2


if(save.results)  {setEPS(width = 10, height = 6); postscript("IVD-SROC.eps")}

par(mfrow = c(2, 4), oma = c(0.2, 3, 0.2, 0.3), mar = c(3, 0.2, 2, 0.2))

##
## SROC
##
col <- 1:4

## A

plot(1-sp, se, type = "p", ylim = c(0,1), xlim = c(0,1), 
     xlab = "", ylab = "")
SROC(est2.par, addon  = TRUE, ncols = col, sroc.type = sauc.type)

legend("bottomright", 
       bty='n',
       legend = c(sprintf("p = %.1f, SAUC = %.3f", p.seq, sauc2)), 
       col = col, pch = 18, pt.cex = 2, cex = legend.cex, 
       lty = rep(1,3))

title("(A)", adj = 0, font.main = 1, cex.main = title.cex)
title(TeX("$(\\hat{c}_1, \\, \\hat{c}_2)$"), cex.main = title.cex)
title(xlab = "FPR", line=2, cex = 0.7)
mtext("TPR", side=2, line=2, at=0.5, cex = 0.7)


## B

plot(1-sp, se, type = "p", ylim = c(0,1), xlim = c(0,1), 
     xlab = "",
     yaxt = "n")
SROC(est11.par, addon  = TRUE, ncols = col, sroc.type = sauc.type)
legend("bottomright", 
       bty='n',
       legend = c(sprintf("p = %.1f, SAUC = %.3f", p.seq, sauc11)), 
       col = col, pch = 18, pt.cex = 2, cex = legend.cex, 
       lty = rep(1,3))
title("(B)", adj = 0, font.main = 1, cex.main = title.cex)
title(TeX("$(c_1, \\,c_2) = (1/\\sqrt{2}, 1/\\sqrt{2})$"), cex.main = title.cex)
title(xlab = "FPR", line=2, cex = 0.7)

## zC

plot(1-sp, se, type = "p", ylim = c(0,1), xlim = c(0,1), 
     xlab = "",
     yaxt = "n")
SROC(est10.par, addon  = TRUE, ncols = col, sroc.type = sauc.type)
legend("bottomright", 
       bty='n',
       legend = c(sprintf("p = %.1f, SAUC = %.3f", p.seq, sauc10)), 
       col = col, pch = 18, pt.cex = 2, cex = legend.cex, 
       lty = rep(1,3))
title("(C)", adj = 0, font.main = 1, cex.main = title.cex)
title(TeX("$(c_1,\\, c_2) = (1,\\, 0)$"), cex.main = title.cex)
title(xlab = "FPR", line=2, cex = 0.7)

## D

plot(1-sp, se, type = "p", ylim = c(0,1), xlim = c(0,1), 
     xlab = "",
     yaxt = "n")
SROC(est01.par, addon = TRUE, ncols = col, sroc.type = sauc.type)
legend("bottomright", 
       bty='n',
       legend = c(sprintf("p = %.1f, SAUC = %.3f", p.seq, sauc01)), 
       col = col, pch = 18, pt.cex = 2, cex = legend.cex, 
       lty = rep(1,3))
title("(D)", adj = 0, font.main = 1, cex.main = title.cex)
title(TeX("$(c_1,\\, c_2) = (0,\\, 1)$"), cex.main = title.cex)
title(xlab = "FPR", line=2, cex = 0.7)


##
## SAUC
##

## E(A)

matplot(t(est.sauc2),ylim=c(0,1), type = "b",lty = c(1,2,2), pch=20, col = c(1, 2,2),
         ylab = "SAUC", xlab = "", xaxt = "n", yaxt = "n")
title(TeX("$(\\hat{c}_1, \\, \\hat{c}_2)$"), cex.main = title.cex)
axis(1, at = 1:10, labels = p.10)
axis(2, at = seq(0, 1, 0.2), labels = seq(0, 1, 0.2))
abline(h=0.5, col="grey54", lty=2)
title("(E)", adj = 0, font.main = 1, cex.main = title.cex)
title(xlab = "p", line=2, cex = 0.7)
mtext("SAUC", side=2, line=2, at=0.5, cex = 0.7)


## F(B)

matplot(t(est.sauc11),ylim=c(0,1), type = "b",lty = c(1,2,2), pch=20, col = c(1, 2,2),
         ylab = "SAUC", xlab = "", xaxt = "n", yaxt = "n")
title(TeX("$(c_1, \\,c_2) = (1/\\sqrt{2}, 1/\\sqrt{2})$"), cex.main = title.cex)
axis(1, at = 1:10, labels = p.10)
abline(h=0.5, col="grey54", lty=2)
title("(F)", adj = 0, font.main = 1, cex.main = title.cex)
title(xlab = "p", line=2, cex = 0.7)


## G(C)

matplot(t(est.sauc10),ylim=c(0,1), type = "b",lty = c(1,2,2), pch=20, col = c(1, 2,2),
         ylab = "SAUC", xlab = "", xaxt = "n", yaxt = "n")
title(TeX("$(c_1, \\,c_2) = (1, \\,0)$"), cex.main = title.cex)
axis(1, at = 1:10, labels = p.10)
# axis(2, at = seq(0.4,1, 0.2), labels = seq(0.4,1, 0.2))
abline(h=0.5, col="grey54", lty=2)
title("(G)", adj = 0, font.main = 1, cex.main = title.cex)
title(xlab = "p", line=2, cex = 0.7)


## H(D)

matplot(t(est.sauc01),ylim=c(0,1), type = "b",lty = c(1,2,2), pch=20, col = c(1, 2,2),
         ylab = "SAUC", xlab = "", xaxt = "n", yaxt = "n")
title(TeX("$(c_1, \\,c_2) = (0, \\,1)$"), cex.main = title.cex)
axis(1, at = 1:10, labels = p.10)
# axis(2, at = seq(0.4,1, 0.2), labels = seq(0.4,1, 0.2))
abline(h=0.5, col="grey54", lty=2)
title("(H)", adj = 0, font.main = 1, cex.main = title.cex)
title(xlab = "p", line=2, cex = 0.7)


par(mfrow = c(1,1))



if(save.results)  dev.off()
```



# PLOT: Probit of $\alpha$ and $\beta$

```{r, fig.width=10, fig.height=4}

ldata <- logit.data(correction(data, type = "single"))

t11 <- (ldata$y1 + ldata$y2)/sqrt(ldata$v1+ldata$v2)
t10 <- (ldata$y1 )/sqrt(ldata$v1)
t01 <- (ldata$y2)/sqrt(ldata$v2)

beta2  <- est2[11,];  alpha2  <- est2[14,]
beta11 <- est11[11,]; alpha11 <- est11[14,]
beta10 <- est10[11,]; alpha10 <- est10[14,]
beta01 <- est01[11,]; alpha01 <- est01[14,]

c1 <- est2[21,]
c2 <- sqrt(1-est2[21,]^2)

ytext <- TeX("$p = \\Phi(\\beta \\, t + \\alpha)$")
title.cex <- 1.2

##
## Plot
##


if(save.results) {setEPS(width = 10, height = 4); postscript("IVD-PROBIT.eps")}

par(mfrow = c(2, 2), oma = c(0.2, 3, 0.2, 0.2), mar = c(3, 0.2, 2, 0.2))


## A

curve(pnorm(beta2[2]*x + alpha2[2]), -5, 15, ylim = c(0,1),
      xlab = "", 
      col=2,
      yaxt='n')
axis(2, at=c(0,0.5,1), labels = c(0,0.5,1))
curve(pnorm(beta2[3]*x + alpha2[3]), -5, 15, add = TRUE, col=3)
curve(pnorm(beta2[4]*x + alpha2[4]), -5, 15, add = TRUE, col=4)

t02 <- (c1[2]*ldata$y1 + c2[2]*ldata$y2)/sqrt(c1[2]^2*ldata$v1+c2[2]^2*ldata$v2)
t03 <- (c1[3]*ldata$y1 + c2[3]*ldata$y2)/sqrt(c1[3]^2*ldata$v1+c2[3]^2*ldata$v2)
t04 <- (c1[4]*ldata$y1 + c2[4]*ldata$y2)/sqrt(c1[4]^2*ldata$v1+c2[4]^2*ldata$v2)
points(t02, rep(0.2, length(t02)), pch="|", col=2, cex = 1)
points(t03, rep(0.1, length(t03)), pch="|", col=3, cex = 1)
points(t04, rep(0,   length(t04)), pch="|", col=4, cex = 1)
title(TeX("$(\\hat{c}_1, \\, \\hat{c}_2)$"), cex.main = title.cex)
legend("topright", 
       bty='n',
       legend = TeX(sprintf("$p = %.1f$", p.seq[-1])), 
       col = 2:4, cex = 1.2, 
       lty = rep(1,3))
title("(A)", adj = 0, font.main = 1, cex.main = title.cex)
mtext(c(ytext), side=2, line=2, at=c(0.5), cex = 0.8)
title(xlab = "t", line=2, cex = 0.7)


## B

curve(pnorm(beta11[2]*x + alpha11[2]), -5, 15,ylim = c(0,1),
      xlab = "", 
      col=2,
      yaxt='n')
curve(pnorm(beta11[3]*x + alpha11[3]), -5, 15, add = TRUE, col=3)
curve(pnorm(beta11[4]*x + alpha11[4]), -5, 15, add = TRUE, col=4)
points(t11, rep(0, length(t11)), pch="|", cex = 1)
title(TeX("$(c_1, \\,c_2) = (1/\\sqrt{2}, 1/\\sqrt{2})$"), cex.main = title.cex)
legend("topright", 
       bty='n',
       legend = TeX(sprintf("$p = %.1f$", p.seq[-1])), 
       col = 2:4, cex = 1.2, 
       lty = rep(1,3))
title("(B)", adj = 0, font.main = 1, cex.main = title.cex)
title(xlab = "t", line=2, cex = 0.7)


## C

curve(pnorm(beta10[2]*x + alpha10[2]), -5, 15,ylim = c(0,1),
      xlab = "", 
      col=2,
      yaxt='n')
axis(2, at=c(0,0.5,1), labels = c(0,0.5,1))
curve(pnorm(beta10[3]*x + alpha10[3]), -5, 15, add = TRUE, col=3)
curve(pnorm(beta10[4]*x + alpha10[4]), -5, 15, add = TRUE, col=4)
points(t10, rep(0, length(t10)), pch="|", cex = 1)
title(TeX("$(c_1, \\,c_2) = (1, \\,0)$"), cex.main = title.cex)
legend("topright", 
       bty='n',
       legend = TeX(sprintf("$p = %.1f$", p.seq[-1])), 
       col = 2:4, cex = 1.2, 
       lty = rep(1,3))
title("(C)", adj = 0, font.main = 1, cex.main = title.cex)
mtext(c(ytext), side=2, line=2, at=c(0.5), cex = 0.8)
title(xlab = "t", line=2, cex = 0.7)


## D

curve(pnorm(beta01[2]*x + alpha01[2]), -5, 15, ylim = c(0,1),
      xlab = "", 
      col=2,
      yaxt='n')
curve(pnorm(beta01[3]*x + alpha01[3]), -5, 15, add = TRUE, col=3)
curve(pnorm(beta01[4]*x + alpha01[4]), -5, 15, add = TRUE, col=4)
points(t01, rep(0, length(t01)), pch="|", cex = 1)
title(TeX("$(c_1, \\,c_2) = (0, \\,1)$"), cex.main = title.cex)
legend("topright", 
       bty='n',
       legend = TeX(sprintf("$p = %.1f$", p.seq[-1])), 
       col = 2:4, cex = 1.2, 
       lty = rep(1,3))
title("(D)", adj = 0, font.main = 1, cex.main = title.cex)
title(xlab = "t", line=2, cex = 0.7)


par(mfrow = c(1, 1))

if(save.results) dev.off()


```



# PLOT: Funnel plot1 (Supp.)


```{r, fig.width=10, fig.height=4,}
data.cc <- correction(data, type = "single")
# ldata   <- logit.data(correction(data, type = "single"))
data.cc1 <- correction(data[data$cutoff.grp==1,], type = "single")
data.cc2 <- correction(data[data$cutoff.grp==2,], type = "single")


#shapes <- ifelse(data.cc$type=="SQ", 21, 24)
# cols <- ifelse(data.cc$cutoff.grp== 1, 21, ifelse(data.cc$cutoff.grp==2, 24, ))
if(save.results)  {setEPS(width = 10, height = 4); postscript("IVD-FUNNEL.eps")}



par(oma = c(6, 2, 0.2, 0.2), mfrow = c(1, 3), mar = c(4, 2, 0.2, 0.2))


##
## ALL
##

## lnDOR
ml.lnDOR <- metabin(TP, with(data.cc, TP+FN), FP, with(data.cc, TN+FP), data = data.cc, sm ="OR", fixed = FALSE)
tf.lndor <- trimfill(ml.lnDOR, fixed = FALSE)
funnel(tf.lndor, xlab = "lnDOR", 
       #pch = c(shapes, rep(1, sum(tf.lndor[["trimfill"]]))),
       bg = data.cc$cutoff.grp+1,
       # col = c(data.cc$cutoff.grp+1, rep(1, sum(tf.lndor[["trimfill"]]))),
       cex = 1.5, studlab = FALSE, backtransf = FALSE,
       # fixed = FALSE, random = TRUE,
       ref = exp(ml.lnDOR$TE.random)
       # level = 0.95,
       # contour = c(0.9, 0.95, 0.99)
)

mtext("Standar Error", side = 2, line = 2, at = 1, cex = 0.7)


## Sens
ml.se <- metabin(TP, with(data.cc, TP+FN), FN, with(data.cc, TP+FN), data = data.cc, sm ="OR", fixed = FALSE)
tf.se <- trimfill(ml.se, fixed = FALSE)
tf.se[["TE"]] <- tf.se[["TE"]]/2
tf.se[["seTE"]] <- tf.se[["seTE"]]/sqrt(2) 
funnel(tf.se, xlab = "logit-sensitivity",
       #pch = c(shapes, rep(1, sum(tf.se[["trimfill"]]))),
       yaxt = FALSE,
       bg = data.cc$cutoff.grp+1,
       cex = 1.5, studlab = FALSE, backtransf = FALSE, 
       ref = exp(ml.se$TE.random)
       # level = 0.95,
       # contour = c(0.9, 0.95, 0.99)
)


## Spec
ml.sp <- metabin(TN, with(data.cc, TN+FP), FP, with(data.cc, TN+FP), data = data.cc, sm ="OR", fixed = FALSE)
tf.sp <- trimfill(ml.sp, fixed = FALSE)
tf.sp[["TE"]] <- tf.sp[["TE"]]/2
tf.sp[["seTE"]] <- tf.sp[["seTE"]]/sqrt(2) 
funnel(tf.sp, xlab = "logit-specificity", fixed = FALSE,
       #pch = c(shapes, rep(1, sum(tf.sp[["trimfill"]]))),
       bg = data.cc$cutoff.grp+1,
       cex = 1.5, studlab = FALSE, backtransf = FALSE,
       ref = exp(ml.sp$TE.random)
       # level = 0.95,
       # contour = c(0.9, 0.95, 0.99)
)


par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0), new = TRUE)
plot(0, 0, type = 'l', bty = 'n', xaxt = 'n', yaxt = 'n')

legend_order <- matrix(1:4, ncol=2, byrow = TRUE)

legend('bottom',
       legend = c("Filled studies", 
                  "Published studies with cutoff values >15 colony forming units",
                  "Published studies with cutoff values >1000 colony forming units", 
                  "Published studies with other cutoffs")[legend_order],
                  # "Semi-quantitative segment cultures",
                  # "Quantitative segment cultures")[legend_order],
       pch = c(1,rep(21, 3))[legend_order],
       pt.bg = c(1:4)[legend_order], 
       xpd = TRUE, 
       horiz = FALSE, 
       cex = 1.2,
       # pt.cex =c(1.2, 0, 1.2, 0, rep(2,4))[legend_order],
       seg.len=2,
       bty = 'n',
       ncol = 2,
       pt.cex = 1.5)

par(mfrow = c(1,1))

if(save.results)  dev.off()

```








```{r, fig.width=10, fig.height=10, include=FALSE,eval=FALSE}

# PLOT: Funnel plot2 (Subgroup)


#data.cc <- correction(data, type = "single")
# ldata   <- logit.data(correction(data, type = "single"))
#data.cc1 <- correction(data[data$cutoff.grp==1,], type = "single")
#data.cc2 <- correction(data[data$cutoff.grp==2,], type = "single")


shapes <- ifelse(data.cc$type=="SQ", 21, 24)
# cols <- ifelse(data.cc$cutoff.grp== 1, 21, ifelse(data.cc$cutoff.grp==2, 24, ))
#if(save.results)  {setEPS(width = 10, height = 10); postscript("IVD-FUNNEL.eps")}



par(oma = c(6,1,1,1), mfrow = c(3, 3), mar = c(4, 4, 3, 1))


##
## ALL
##

## lnDOR
ml.lnDOR <- metabin(TP, with(data.cc, TP+FN), FP, with(data.cc, TN+FP), data = data.cc, sm ="OR", fixed = FALSE)
tf.lndor <- trimfill(ml.lnDOR, fixed = FALSE)
funnel(tf.lndor, xlab = "lnDOR", 
       #pch = c(shapes, rep(1, sum(tf.lndor[["trimfill"]]))),
       bg = data.cc$cutoff.grp+1,
       # col = c(data.cc$cutoff.grp+1, rep(1, sum(tf.lndor[["trimfill"]]))),
       cex = 1.5, studlab = FALSE, backtransf = FALSE,
       ref = exp(ml.lnDOR$TE.random),
       level = 0.95,
       contour = c(0.9, 0.95, 0.99)
)


## Sens
ml.se <- metabin(TP, with(data.cc, TP+FN), FN, with(data.cc, TP+FN), data = data.cc, sm ="OR", fixed = FALSE)
tf.se <- trimfill(ml.se, fixed = FALSE)
tf.se[["TE"]] <- tf.se[["TE"]]/2
tf.se[["seTE"]] <- tf.se[["seTE"]]/sqrt(2) 
funnel(tf.se, xlab = "logit(sensitivity)",
       #pch = c(shapes, rep(1, sum(tf.se[["trimfill"]]))),
       bg = data.cc$cutoff.grp+1,
       cex = 1.5, studlab = FALSE, backtransf = FALSE,
       ref = exp(ml.se$TE.random),
       level = 0.95,
       contour = c(0.9, 0.95, 0.99)
)


## Spec
ml.sp <- metabin(TN, with(data.cc, TN+FP), FP, with(data.cc, TN+FP), data = data.cc, sm ="OR", fixed = FALSE)
tf.sp <- trimfill(ml.sp, fixed = FALSE)
tf.sp[["TE"]] <- tf.sp[["TE"]]/2
tf.sp[["seTE"]] <- tf.sp[["seTE"]]/sqrt(2) 
funnel(tf.sp, xlab = "logit(specificity)", fixed = FALSE,
       #pch = c(shapes, rep(1, sum(tf.sp[["trimfill"]]))),
       bg = data.cc$cutoff.grp+1,
       cex = 1.5, studlab = FALSE, backtransf = FALSE,
       ref = exp(ml.sp$TE.random),
       level = 0.95,
       contour = c(0.9, 0.95, 0.99)
)

##
## GROUP1 >15
##

## lnDOR

ml.lnDOR <- metabin(TP, with(data.cc1, TP+FN), FP, with(data.cc1, TN+FP), data = data.cc1, sm ="OR", fixed = FALSE)
tf.lndor <- trimfill(ml.lnDOR, fixed = FALSE)
funnel(tf.lndor, xlab = "lnDOR", 
       #pch = c(shapes, rep(1, sum(tf.lndor[["trimfill"]]))),
       bg = data.cc1$cutoff.grp+1,
       # col = c(data.cc$cutoff.grp+1, rep(1, sum(tf.lndor[["trimfill"]]))),
       cex = 1.5, studlab = FALSE, backtransf = FALSE,
       ref = exp(ml.lnDOR$TE.random),
       level = 0.95,
       contour = c(0.9, 0.95, 0.99)
)



## Sens
ml.se <- metabin(TP, with(data.cc1, TP+FN), FN, with(data.cc1, TP+FN), data = data.cc1, sm ="OR", fixed = FALSE)
tf.se <- trimfill(ml.se, fixed = FALSE)
tf.se[["TE"]] <- tf.se[["TE"]]/2
tf.se[["seTE"]] <- tf.se[["seTE"]]/sqrt(2) 
funnel(tf.se, xlab = "logit(sensitivity)",
       #pch = c(shapes, rep(1, sum(tf.se[["trimfill"]]))),
       bg = data.cc1$cutoff.grp+1,
       cex = 1.5, studlab = FALSE, backtransf = FALSE,
       ref = exp(ml.se$TE.random),
       level = 0.95,
       contour = c(0.9, 0.95, 0.99)
)


## Spec
ml.sp <- metabin(TN, with(data.cc1, TN+FP), FP, with(data.cc1, TN+FP), data = data.cc1, sm ="OR", fixed = FALSE)
tf.sp <- trimfill(ml.sp, fixed = FALSE)
tf.sp[["TE"]] <- tf.sp[["TE"]]/2
tf.sp[["seTE"]] <- tf.sp[["seTE"]]/sqrt(2) 
funnel(tf.sp, xlab = "logit(specificity)", fixed = FALSE,
       #pch = c(shapes, rep(1, sum(tf.sp[["trimfill"]]))),
       bg = data.cc1$cutoff.grp+1,
       cex = 1.5, studlab = FALSE, backtransf = FALSE,
       ref = exp(ml.sp$TE.random),
       level = 0.95,
       contour = c(0.9, 0.95, 0.99)
)

## lnDOR

ml.lnDOR <- metabin(TP, with(data.cc2, TP+FN), FP, with(data.cc2, TN+FP), data = data.cc2, sm ="OR", fixed = FALSE)
tf.lndor <- trimfill(ml.lnDOR, fixed = FALSE)
funnel(tf.lndor, xlab = "lnDOR", 
       #pch = c(shapes, rep(1, sum(tf.lndor[["trimfill"]]))),
       bg = data.cc2$cutoff.grp+1,
       # col = c(data.cc$cutoff.grp+1, rep(1, sum(tf.lndor[["trimfill"]]))),
       cex = 1.5, studlab = FALSE, backtransf = FALSE,
       ref = exp(ml.lnDOR$TE.random),
       level = 0.95,
       contour = c(0.9, 0.95, 0.99)
)


## Sens
ml.se <- metabin(TP, with(data.cc2, TP+FN), FN, with(data.cc2, TP+FN), data = data.cc2, sm ="OR", fixed = FALSE)
tf.se <- trimfill(ml.se, fixed = FALSE)
tf.se[["TE"]] <- tf.se[["TE"]]/2
tf.se[["seTE"]] <- tf.se[["seTE"]]/sqrt(2) 
funnel(tf.se, xlab = "logit(sensitivity)",
       #pch = c(shapes, rep(1, sum(tf.se[["trimfill"]]))),
       bg = data.cc2$cutoff.grp+1,
       cex = 1.5, studlab = FALSE, backtransf = FALSE,
       ref = exp(ml.se$TE.random),
       level = 0.95,
       contour = c(0.9, 0.95, 0.99)
)


## Spec
ml.sp <- metabin(TN, with(data.cc2, TN+FP), FP, with(data.cc2, TN+FP), data = data.cc2, sm ="OR", fixed = FALSE)
tf.sp <- trimfill(ml.sp, fixed = FALSE)
tf.sp[["TE"]] <- tf.sp[["TE"]]/2
tf.sp[["seTE"]] <- tf.sp[["seTE"]]/sqrt(2) 
funnel(tf.sp, xlab = "logit(specificity)", fixed = FALSE,
       #pch = c(shapes, rep(1, sum(tf.sp[["trimfill"]]))),
       bg = data.cc2$cutoff.grp+1,
       cex = 1.5, studlab = FALSE, backtransf = FALSE,
       ref = exp(ml.sp$TE.random),
       level = 0.95,
       contour = c(0.9, 0.95, 0.99)
)

par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(1, 0, 1, 0), new = TRUE)
plot(0, 0, type = 'l', bty = 'n', xaxt = 'n', yaxt = 'n')

legend_order <- matrix(1:4, ncol=2, byrow = TRUE)

legend('bottom',
       legend = c("Filled studies", 
                  "Published studies with cutoff values >15 colony forming units",
                  "Published studies with cutoff values >1000 colony forming units", 
                  "Published studies with other cutoffs")[legend_order],
                  # "Semi-quantitative segment cultures",
                  # "Quantitative segment cultures")[legend_order],
       pch = c(1,rep(21, 3))[legend_order],
       pt.bg = c(1:4)[legend_order], 
       xpd = TRUE, 
       horiz = FALSE, 
       cex = 1.2,
       # pt.cex =c(1.2, 0, 1.2, 0, rep(2,4))[legend_order],
       seg.len=2,
       bty = 'n',
       ncol = 2,
       pt.cex = 1.5)

par(mfrow = c(1,1))

if(save.results)  dev.off()

```



